[package]
name = "rrr-cli"
version = "0.3.2"
edition = "2021"

[dependencies]
anyhow = "1"
aws-config = "0.46"
aws-sdk-s3 = "0.16"
bytes = "1"
clap = { version = "3.2", features = ["cargo"] }
console = "0.15"
rrr = { path = "..", version = "=0.3.2" }
tokio = { version = "1.14", features = ["full"] } # avoiding RUSTSEC-2021-0124
url = "2"

[target.'cfg(unix)'.dependencies]
pager = "0.16"
which = "4"
