[package]
name = "rrr-cli"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1"
aws-config = "0.13"
aws-sdk-s3 = "0.13"
bytes = "1"
clap = { version = "3.2", features = ["cargo"] }
console = "0.15"
rrr = { path = "..", version = "=0.3.0" }
tokio = { version = "1", features = ["full"] }
url = "2"

[target.'cfg(unix)'.dependencies]
pager = "0.16"
which = "4"
