[package]
name = "rrr-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3.1", features = ["cargo"] }
console = "0.15"
rrr = { path = "..", version = "=0.1.0" }

[target.'cfg(unix)'.dependencies]
pager = "0.16"
which = "4"
